### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by IgorBezanovic** [SVasilev/http-headers-validation#1]
Hi,

On a project I'm currently working on, we faced a migration from common JS to TypeScript. We also use your library, however it does not support TypeScript.

I am opening this issue to improve this package. I also offer my contribution to solving this.

**Comment by SVasilev** [comment]
Hello,
I am not fluent in TypeScript but I will gladly accept a PR if you are willing to contribute it to the project 👍

**Comment by SVasilev** [comment]
Hey, I just published version 0.0.2 - Thanks for the contribution! 
Can you check if everything is working as expected in your project after updating to 0.0.2 so I am sure I haven't messed up the module for developers who are using the library? Thanks!

**Comment by IgorBezanovic** [comment]
It was my pleasure!

You didn't mess up the module, because they use version 0.0.1, so the previous version definitely works for them. In the coming days I will verify the new version, I honestly firmly believe that everything is as it should be :)

**Comment by SVasilev** [comment]
Yeah, I am sure I did not mess it up for users of 0.0.1.
I thought your team was going to pick up the new version as soon as it is live (e.g. today) and report if there are any problems.
But I am not in a hurry. Please report (if it works or not) whenever you or your team starts using 0.0.2.
Best regards!
